config/routes.rb
RestApiApp::Application.routes.draw do
  resources :proxy_images

  resources :users

end

app/models/proxy_image.rb
class ProxyImage < ActiveRecord::Base
  attr_accessible :content, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/proxy_images_controller.rb
class ProxyImagesController < ApplicationController
  # GET /proxy_images
  # GET /proxy_images.json
  def index
    @proxy_images = ProxyImage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proxy_images }
    end
  end

  # GET /proxy_images/1
  # GET /proxy_images/1.json
  def show
    @proxy_image = ProxyImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proxy_image }
    end
  end

  # GET /proxy_images/new
  # GET /proxy_images/new.json
  def new
    @proxy_image = ProxyImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proxy_image }
    end
  end

  # GET /proxy_images/1/edit
  def edit
    @proxy_image = ProxyImage.find(params[:id])
  end

  # POST /proxy_images
  # POST /proxy_images.json
  def create
    @proxy_image = ProxyImage.new(params[:proxy_image])

    respond_to do |format|
      if @proxy_image.save
        format.html { redirect_to @proxy_image, notice: 'Proxy image was successfully created.' }
        format.json { render json: @proxy_image, status: :created, location: @proxy_image }
      else
        format.html { render action: "new" }
        format.json { render json: @proxy_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proxy_images/1
  # PUT /proxy_images/1.json
  def update
    @proxy_image = ProxyImage.find(params[:id])

    respond_to do |format|
      if @proxy_image.update_attributes(params[:proxy_image])
        format.html { redirect_to @proxy_image, notice: 'Proxy image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proxy_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proxy_images/1
  # DELETE /proxy_images/1.json
  def destroy
    @proxy_image = ProxyImage.find(params[:id])
    @proxy_image.destroy

    respond_to do |format|
      format.html { redirect_to proxy_images_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proxy_images_helper.rb
module ProxyImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestApiApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/proxy_images/_form.html.erb
<%= form_for(@proxy_image) do |f| %>
  <% if @proxy_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proxy_image.errors.count, "error") %> prohibited this proxy_image from being saved:</h2>

      <ul>
      <% @proxy_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.file_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proxy_images/edit.html.erb
<h1>Editing proxy_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @proxy_image %> |
<%= link_to 'Back', proxy_images_path %>

app/views/proxy_images/index.html.erb
<h1>Listing proxy_images</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proxy_images.each do |proxy_image| %>
  <tr>
    <td><%= proxy_image.content %></td>
    <td><%= proxy_image.user_id %></td>
    <td><%= link_to 'Show', proxy_image %></td>
    <td><%= link_to 'Edit', edit_proxy_image_path(proxy_image) %></td>
    <td><%= link_to 'Destroy', proxy_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Proxy image', new_proxy_image_path %>

app/views/proxy_images/new.html.erb
<h1>New proxy_image</h1>

<%= render 'form' %>

<%= link_to 'Back', proxy_images_path %>

app/views/proxy_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @proxy_image.content %>
</p>

<p>
  <b>User:</b>
  <%= @proxy_image.user_id %>
</p>


<%= link_to 'Edit', edit_proxy_image_path(@proxy_image) %> |
<%= link_to 'Back', proxy_images_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>